<!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label">Dashboard</li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-speedometer menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="./Home.aspx">Home</a></li>
                            <!-- <li><a href="./index-2.html">Home 2</a></li> -->
                        </ul>
                    </li>       
                    <li class="nav-label">Forms</li>
                  <li>
                    <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                      <i class="icon-note menu-icon"></i>
                      <span class="nav-text">Forms</span>
                    </a>
                    <ul aria-expanded="false">
                      <li>
                        <a href="./VendorRegistration.aspx">Vendor Registration </a>
                      </li>
                      <li>
                        <a href="./VendorAccountStatement.aspx">Vendor Account Statement </a>
                      </li>
                      <li>
                        <a href="./Vendor_Payment.aspx">Vendor Payment</a>
                      </li>
                      <li>
                        <a href="./Vendor_Deposit.aspx">Vendor Deposit</a>
                      </li>
                      <li>
                        <a href="./Vendor_PO_Details.aspx">Vendor PO Details</a>
                      </li>
                      <li>
                        <a href="./Vendor_Movement.aspx">Vendor Movement</a>
                      </li>
                    </ul>
                  </li>  
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->